variables:
  url: https://downloads.sourceforge.net/project/msys2/Base/x86_64/msys2-base-x86_64-20180531.tar.xz
  sha256: 4e799b5c3efcf9efcb84923656b7bcff16f75a666911abd6620ea8e5e1e9870c

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- powershell: |
    function Start-NativeCommand ([scriptblock] Command) {
      $eap = $script:ErrorActionPreference
      $script:ErrorActionPreference = 'Continue'
      try {
        & $command 2>&1
        if ($LASTEXITCODE -ne 0) {
          throw "Native command returns $LASTEXITCODE: $command"
        }
      } finally {
        $script:ErrorActionPreference = $eap
      }
    }
    (New-Object System.Net.WebClient).DownloadFile($env:URL, (Join-Path (Get-Location) msys2.tar.xz))
    $hash = Get-FileHash msys2.tar.xz -Algorithm SHA256
    if ($hash.Hash -ine $env:SHA256) {
      Write-Error "Hash mismatch"
      & file msys2.tar.xz
      Write-Output $hash
      exit 1
    }
    & tar xf msys2.tar.xz
    Start-NativeCommand { & msys64\usr\bin\bash.exe -lc exit }
    & msys64\usr\bin\bash.exe -lc 'pacman -Syuu --noconfirm'
    & msys64\usr\bin\bash.exe -lc 'pacman -Suu --noconfirm'
  displayName: 'Download and initialize MSYS2'
