variables:
  url: https://downloads.sourceforge.net/project/msys2/Base/x86_64/msys2-base-x86_64-20180531.tar.xz
  sha256: 4e799b5c3efcf9efcb84923656b7bcff16f75a666911abd6620ea8e5e1e9870c

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- script: |
    curl -fLSC - -o msys2.tar.xz $(url)
    echo $(sha256) msys2.tar.xz| sha256sum -c || exit 1
    tar xf msys2.tar.xz
    msys64/usr/bin/bash.exe -lc exit
    msys64/usr/bin/bash.exe -lc "pacman -Syuu --noconfirm"
    msys64/usr/bin/bash.exe -lc "pacman -Suu --noconfirm"
  displayName: 'Download and initialize MSYS2'
