variables:
  url: https://downloads.sourceforge.net/project/msys2/Base/x86_64/msys2-base-x86_64-20180531.tar.xz
  sha256: 4e799b5c3efcf9efcb84923656b7bcff16f75a666911abd6620ea8e5e1e9870c

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- bash: |
    set -ex
    curl -Lf -Ss -C - -o msys2.tar.xz $URL
    echo $SHA256 msys2.tar.xz | sha256sum -c
    tar xf msys2.tar.xz
    cmd //c 'msys64\usr\bin\bash.exe' -lc exit
    cmd //c 'msys64\usr\bin\bash.exe' -lc 'pacman -Syuu --noconfirm'
    cmd //c 'msys64\usr\bin\bash.exe' -lc 'pacman -Suu --noconfirm'
- powershell: |
    exit 0
    function exec ([scriptblock] $block) {
      Write-Host ('> Running ' + "$block".Trim()) -ForegroundColor Blue
      $eap = $Script:ErrorActionPreference
      $Script:ErrorActionPreference = 'Continue'
      & $block 2>&1 | % { "$_" }
      if ($LASTEXITCODE -ne 0) {
        throw "Exited with code $LASTEXITCODE"
      }
      $Script:ErrorActionPreference = $eap
    }
    Write-Host '> Downloading $env:URL'
    (New-Object System.Net.WebClient).DownloadFile($env:URL, (Join-Path (Get-Location) msys2.tar.xz))
    $hash = Get-FileHash msys2.tar.xz -Algorithm SHA256
    if ($hash.Hash -ine $env:SHA256) {
      throw "Hash mismatch for $(file msys2.tar.xz)"
    }
    exec { tar xf msys2.tar.xz }
    exec { msys64\usr\bin\bash.exe -lc exit }
    exec { msys64\usr\bin\bash.exe -lc 'pacman -Syuu --noconfirm' }
    exec { msys64\usr\bin\bash.exe -lc 'pacman -Suu --noconfirm' }
  displayName: 'Download and initialize MSYS2'
