variables:
  url: https://downloads.sourceforge.net/project/msys2/Base/x86_64/msys2-base-x86_64-20180531.tar.xz
  sha256: 4e799b5c3efcf9efcb84923656b7bcff16f75a666911abd6620ea8e5e1e9870c
  packages: >
    mingw-w64-i686-nsis
    mingw-w64-i686-python2-gobject
    mingw-w64-i686-python2-cairo
    mingw-w64-i686-python2-pip
    mingw-w64-i686-gtk3
    mingw-w64-i686-gdk-pixbuf2
    mingw-w64-i686-gstreamer
    mingw-w64-i686-gst-plugins-base
    mingw-w64-i686-gst-plugins-good
    mingw-w64-i686-gst-plugins-bad
    mingw-w64-i686-gst-libav
    mingw-w64-i686-gst-plugins-ugly
    mingw-w64-i686-librsvg
    make
    git
    tar
    mingw-w64-i686-python2-bsddb3

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- bash: |
    set -ex
    curl -Lf -Ss -C - -o msys2.tar.xz $URL
    echo $SHA256 msys2.tar.xz | sha256sum -c
    tar xf msys2.tar.xz
    cmd //c 'msys64\usr\bin\bash.exe' -lc exit
    cmd //c 'msys64\usr\bin\bash.exe' -lc 'pacman -Syuu --noconfirm'
    mkdir -p build/home
    mkdir -p build/tmp
    mkdir -p build/var/lib/pacman
    mkdir -p build/var/log
    cmd //c 'msys64\usr\bin\bash.exe' -lc "pacman --root build --noconfirm -Su"
    cmd //c 'msys64\usr\bin\bash.exe' -lc "pacman --root build --noconfirm -S base $PACKAGES"
    time tar cf exaile-binenv-win.tar.xz --strip-components=1 build
    du -csh exaile-binenv-win.tar.xz
  displayName: 'Create Exaile binenv'
