variables:
  url: https://downloads.sourceforge.net/project/msys2/Base/x86_64/msys2-base-x86_64-20180531.tar.xz
  sha256: 4e799b5c3efcf9efcb84923656b7bcff16f75a666911abd6620ea8e5e1e9870c
  packages: >
    mingw-w64-i686-gtk3
    mingw-w64-x86_64-gtk3
    mingw-w64-i686-python2-gobject
    mingw-w64-x86_64-python2-gobject

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- bash: |
    set -ex
    curl -Lf -Ss -C - -o msys2.tar.xz $URL
    echo $SHA256 msys2.tar.xz | sha256sum -c
    tar xf msys2.tar.xz
    cmd //c 'msys64\usr\bin\bash.exe' -lc exit
    cmd //c 'msys64\usr\bin\bash.exe' -lc 'pacman -Syuu --noconfirm'
    cmd //c 'msys64\usr\bin\bash.exe' -lc "pacman -S --noconfirm $PACKAGES"
    time tar cf exaile-binenv-win32.tar.xz --strip-components=1 msys64/mingw32
    time tar cf exaile-binenv-win64.tar.xz --strip-components=1 msys64/mingw64
  displayName: 'Build Exaile binenv'
