variables:
  url: https://downloads.sourceforge.net/project/msys2/Base/x86_64/msys2-base-x86_64-20180531.tar.xz
  sha256: 4e799b5c3efcf9efcb84923656b7bcff16f75a666911abd6620ea8e5e1e9870c

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- powershell: |
    Invoke-WebRequest $env:URL -OutFile msys2.tar.xz
    if ((Get-FileHash msys2.tar.xz SHA256) -ine $env:SHA256) {
      Write-Error "Hash mismatch"
      exit 1
    }
    tar xf msys2.tar.xz
    msys64\usr\bin\bash.exe -lc exit
    msys64\usr\bin\bash.exe -lc 'pacman -Syuu --noconfirm'
    msys64\usr\bin\bash.exe -lc 'pacman -Suu --noconfirm'
  displayName: 'Download and initialize MSYS2'
