variables:
  url: https://downloads.sourceforge.net/project/msys2/Base/x86_64/msys2-base-x86_64-20180531.tar.xz
  sha256: 4e799b5c3efcf9efcb84923656b7bcff16f75a666911abd6620ea8e5e1e9870c

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- script: |
    curl -Lf1 -Ss -C - -o msys2.tar.xz $(url) || exit 1
    echo $(sha256) msys2.tar.xz> checksum.txt || exit 2
    dos2unix checksum.txt || exit 2
    sha256sum -c checksum.txt || exit 2
    tar xf msys2.tar.xz || exit 3
    msys64/usr/bin/bash.exe -lc exit || exit 3
    msys64/usr/bin/bash.exe -lc "pacman -Syuu --noconfirm" || exit 3
    msys64/usr/bin/bash.exe -lc "pacman -Suu --noconfirm" || exit 3
  displayName: 'Download and initialize MSYS2'
