variables:
  url: https://downloads.sourceforge.net/project/msys2/Base/x86_64/msys2-base-x86_64-20180531.tar.xz
  sha256: 4e799b5c3efcf9efcb84923656b7bcff16f75a666911abd6620ea8e5e1e9870c
  packages: >
    git
    make
    mingw-w64-i686-gdk-pixbuf2
    mingw-w64-i686-gst-libav
    mingw-w64-i686-gst-plugins-bad
    mingw-w64-i686-gst-plugins-base
    mingw-w64-i686-gst-plugins-good
    mingw-w64-i686-gst-plugins-ugly
    mingw-w64-i686-gstreamer
    mingw-w64-i686-gtk3
    mingw-w64-i686-nsis
    mingw-w64-i686-python2-bsddb3
    mingw-w64-i686-python2-cairo
    mingw-w64-i686-python2-gobject
    mingw-w64-i686-python2-pip
    mingw-w64-i686-librsvg
    tar
  exclude: |
    '*.a'
    '*.pyc'
    '*.pyo'
    mingw32/include
    mingw32/share/doc
    mingw32/share/gtk-doc
    mingw32/share/man
    mingw32/share/OpenCV
    mingw32/share/opencv4
    usr/share/doc
    usr/share/locale
    usr/share/man
    usr/share/vim

trigger:
- master

pool:
  vmImage: windows-2019

steps:
- bash: |
    set -ex
    curl -Lf -Ss -C - -o msys2.tar.xz $URL
    echo $SHA256 msys2.tar.xz | sha256sum -c
    tar -xf msys2.tar.xz
    # Calling bash directly doesn't work (clash between cygwin dlls), so go through cmd
    cmd //c 'msys64\usr\bin\bash.exe' -lc exit  # Perform initial setup
    cmd //c 'msys64\usr\bin\bash.exe' -lc 'pacman --noconfirm -Syuu'  # Ensure up-to-date pacman etc.
    # pacman doesn't work on /c/..., so the build dir must be inside msys root
    mkdir -p msys64/build/var/lib/pacman
    cmd //c 'msys64\usr\bin\bash.exe' -lc "pacman --noconfirm -r /build -Sy $PACKAGES"
    (cd msys64/build && time tar -caf ../../exaile-binenv-win.tar.xz -X <(echo "$EXCLUDE") *)
    du -csh exaile-binenv-win.tar.xz
  displayName: Create Exaile binenv
